### ISSUE TITLE
Error while using www. in the twitter url

### ISSUE THREAD

**Issue by SatyamKr07** [sur950/any_link_preview#35] opened 2022-07-07 11:05 UTC
When i use the url "https://www.twitter.com" it is showing error. 
But when I am using url "https://twitter.com" (without www.) it is not showing error and I am able to see the link preview.

Here's the error :
D/InsetsController(11360): show(ime(), fromIme=true)
I/flutter (11360): Error while retrieving cache data => type 'Null' is not a subtype of type 'String'
D/InputMethodManager(11360): showSoftInput() view=io.flutter.embedding.android.FlutterView{bfbbd4d VFE...... .F...... 0,0-1080,2154 #2 aid=1073741824} flags=0 reason=SHOW_SOFT_INPUT

**Comment by woogi-kang** [comment] 2022-07-28 07:33
I am also having this error with notion url.

**Comment by sur950** [comment] 2022-08-04 05:15
Usually site builders will add a `CName` entry to their DNS which redirects to `domain.com` when someone hits`www.domain.com`.

So logically there won't be any metadata for `www.` links, we generally replace www.domain.com with domain.com while fetching the meta info. 

I forgot to do that. I will add that in my next release, till then you can do this replacement in your code before passing it to the preview component. 

Simply find for `host` and if the host domain has www. then simply replace that with an empty string. And append `https://` at the beginning. That should solve your issue.


Cheers,
Suresh

**Comment by harmeet-sidhu** [comment] 2023-01-03 13:08
I am having issues with all Twitter URLs whether they start with `www.` or not. I think the issue is on the Twitter side because metadata extractor websites also show errors for twitter URLs.

**Comment by sur950** [comment] 2023-06-05 14:12
I hope you found the RCA for the links that you are trying. I am closing the issue. Feel free to open a new one when you find this is an issue with our package while the same is loading in metadata extractor websites.

**Closed as completed by sur950** 2023-06-05 14:12 UTC
