### ISSUE TITLE
Preview and getMetadata function aren't working with TikTok URL

### ISSUE THREAD

**Issue by AndreVicenteW** [sur950/any_link_preview#47] opened 2023-01-11 13:55 UTC
I'm trying to open a TikTok preview but it doesn't work.
```
AnyLinkPreview(
       link: "https://tiktok.com/@andcarli/video/7165212193921715462?is_from_webapp=1&sender_device=mobile&sender_web_id=7187368554588751365",
)
```
The method `getMetadata` doesn't work too.
![Screenshot 2023-01-11 at 10 49 21](https://user-images.githubusercontent.com/17278092/211822826-b8be880b-4f58-4456-8aa5-cf66aeed92be.png)

**Comment by sur950** [comment] 2024-04-10 11:22
Hi, This is fixed in Version 3.0.2 and the description is not coming in the metadata for most of the TikTok videos. I tried using proxy URLs and VPN to check this issue.

Thanks for making plugin more stronger. Please check with V 3.0.2 and feel free to open the issue if the issue is still there.

**Closed by sur950** 2024-04-10 11:22 UTC
