### ISSUE TITLE
Preview issue while using x.com

### ISSUE THREAD

**Issue by nilsorathiya** [sur950/any_link_preview#57] opened 2023-08-14 05:55 UTC
Having an issue while generating a preview for, 
https://x.com/premierleague/status/1690778132922396673?s=46&t=71tXBSvhA7KzNBMe05rQ4w

::::ERROR::::
`AnyLinkPreview - Error in https://x.com/premierleague/status/1690778132922396673?s=46&t=71tXBSvhA7KzNBMe05rQ4w response (ClientException: Redirect loop detected, uri=/premierleague/status/1690778132922396673?s=46&t=71tXBSvhA7KzNBMe05rQ4w)`

**Comment by Add00w** [comment] 2023-09-18 10:23
Twitter links are broken @sur950  
- Error while retrieving cache data => type 'Null' is not a subtype of type 'String'
- AnyLinkPreview - Error in https://twitter.com/Add00w/status/1684578272464744453?t=xKHi896H3xg3o-4lXjVLPg&s=19 response (Redirect loop detected)

**Comment by Add00w** [comment] 2023-09-20 14:36
> Same error here

It seems twitter changed something 😀

**Comment by egler321** [comment] 2023-09-20 14:55
> > Same error here
> 
> It seems twitter changed something 😀

elon musk playing with us

**Comment by sur950** [comment] 2024-04-10 13:38
> Twitter links are broken @sur950
> 
> * Error while retrieving cache data => type 'Null' is not a subtype of type 'String'
> * AnyLinkPreview - Error in https://twitter.com/Add00w/status/1684578272464744453?t=xKHi896H3xg3o-4lXjVLPg&s=19 response (Redirect loop detected)

Hi, It seems working for me. Can you give a try with the latest version & let me know the observations
[any_link_preview: ^3.0.2](https://pub.dev/packages/any_link_preview)

**Comment by sur950** [comment] 2024-05-23 11:10
I am hoping the issue is resolved in the latest version. I am closing the bug with the same expectations.

Feel free to log a new one if the issue persist, Thanks!

**Closed by sur950** 2024-05-23 11:10 UTC
Labels: Waiting for user response
